# Generated by Django 4.2.2 on 2023-06-08 16:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=40)),
                ('gif', models.URLField(default='https://giphy.com/clips/theoffice-3rS8HpFMbQzQ7p925V')),
                ('duration', models.IntegerField(default=30)),
                ('rest', models.IntegerField(default=10)),
                ('iterations', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('exercises', models.ManyToManyField(to='qfsapi.exercise')),
                ('workout_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qfsapi.workoutgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.URLField(default='https://www.nicepng.com/png/detail/1011-10113425_profile-clipart-generic-user-circle.png')),
                ('motivation', models.CharField(max_length=50)),
                ('public', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qfsapi.workoutgroup'),
        ),
        migrations.CreateModel(
            name='CompletedWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qfsapi.member')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qfsapi.workout')),
            ],
        ),
    ]
