# Generated by Django 4.2.2 on 2023-06-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qfsapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='duration',
            field=models.IntegerField(default=0, max_length=40),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='gif',
            field=models.URLField(verbose_name='https://giphy.com/clips/theoffice-3rS8HpFMbQzQ7p925V'),
        ),
        migrations.AlterField(
            model_name='member',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
