# Generated by Django 4.2.2 on 2023-06-08 16:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qfsapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qfsapi.member')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qfsapi.workout')),
            ],
        ),
    ]
