# Generated by Django 4.2.2 on 2023-06-16 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qfsapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qfsapi.member'),
        ),
    ]
