# Generated by Django 4.2.2 on 2023-06-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qfsapi', '0002_alter_workoutexercise_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercise',
            name='order',
            field=models.IntegerField(),
        ),
    ]
