# Generated by Django 4.2.2 on 2023-06-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qfsapi', '0002_customworkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(related_name='workout_exercises', to='qfsapi.exercise'),
        ),
    ]
