# Generated by Django 4.2.2 on 2023-06-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qfsapi', '0002_exercise_duration_alter_exercise_gif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='iterations',
            field=models.IntegerField(default=3, max_length=40),
        ),
        migrations.AddField(
            model_name='exercise',
            name='rest',
            field=models.IntegerField(default=10, max_length=40),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='duration',
            field=models.IntegerField(default=30, max_length=40),
        ),
    ]
