# Generated by Django 4.2.2 on 2023-06-22 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qfsapi', '0003_alter_workoutexercise_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='iterations',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='rest',
        ),
    ]
