# Generated by Django 4.2.2 on 2023-06-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qfsapi', '0003_exercise_iterations_exercise_rest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='duration',
            field=models.IntegerField(default=30, max_length=10),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='iterations',
            field=models.IntegerField(default=3, max_length=10),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='rest',
            field=models.IntegerField(default=10, max_length=10),
        ),
    ]
