# Generated by Django 4.2.2 on 2023-06-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qfsapi', '0005_workout_exercises_alter_exercise_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutgroup',
            name='exercise',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='gif',
            field=models.URLField(default='https://giphy.com/clips/theoffice-3rS8HpFMbQzQ7p925V'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(to='qfsapi.exercise'),
        ),
    ]
