# Generated by Django 4.2.2 on 2023-06-07 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qfsapi', '0006_remove_workoutgroup_exercise_alter_exercise_gif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='workout_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qfsapi.workoutgroup'),
            preserve_default=False,
        ),
    ]
